quotes = [
    "It is best to begin at the beginning.",
    "The purpose of life is to contribute in some way to making things better.",
    "What you seek is seeking you.",
    "If ever you feel like an animal among men, be a lion.",
    "The guest will judge better of a feast than the cook.",
    "Never let your memories be greater than your dreams.",
    "Success is the progressive realization of a worthy goal or ideal.",
    "Those who know, do. Those that understand, teach.",
    "It is those who concentrate on but one thing at a time who advance in this world.",
    "It is not the knowing that is difficult, but the doing. ",
    "Freedom is the only worthy goal in life. It is won by disregarding things that lie beyond our control.",
    "Life's too mysterious to take too serious.",
    "He who leaves the game wins it.",
    "No one returns from a long journey the same person they were before.",
    "The greater the impact you want to make, the greater your influence needs to be.",
    "The only people without problems are those in cemeteries.",
    "Wherever you are is the entry point.",
    "Believe and you're halfway there.",
    "Be thankful for everything that happens in your life; it's all an experience.",
    "The enemy is a very good teacher.",
    "Wit is educated insolence.",
    "Things may come to those who wait, but only the things left by those who hustle.",
    "Heaven is right where you are standing.",
    "Have the fearless attitude of a hero and the loving heart of a child.",
    "Confidence is like a dragon where, for every head cut off, two more heads grow back.",
    "If it entertains you now but will bore you someday, it's a distraction. Keep looking.",
    "Life and the simple beauty of it is too good to pass up.",
    "You cannot always control what goes on outside. But you can always control what goes on inside. ",
    "What's the point in being smart enough to read, if everything you read makes you dumb?",
    "Never give up work. Work gives you meaning and purpose and life is empty without it.",
    "A person without a sense of humor is like a wagon without springs, jolted by every pebble in the road.",
    "If you love life, don't waste time, for time is what life is made up of. ",
    "To live outside the law, you must be honest. ",
    "There is no value in anything until it is finished. ",
    "Argue for your limitations and sure enough, they're yours.",
    "The fear of death is more to be feared, than death itself.",
    "We meet ourselves time and again in a thousand disguises on the path of life.",
    "The fear of death is more to be feared, than death itself.",
    "The soul should always stand ajar, ready to welcome the ecstatic experience.",
    "Not doing it is certainly the best way to not getting it.  ",
    "Failure is acceptable. Not trying is a whole different ball park.",
    "The decisions of our past are the architects of our present.",
    "Remain calm. Be kind.",
    "Everyone has a sense of humor. If you don't laugh at jokes, you probably laugh at opinions.",
    "Never whine, never complain, never try to justify yourself.",
    "We must create our own world or we will die from inaction.",
    "By changing nothing, nothing changes.",
    "Take care of your body. It's the only place you have to live.",
    "When obstacles arise, you change your direction to reach your goal; you do not change your decision to get there.",
    "Many of life's failures are people who did not realize how close they were to success when they gave up.",
    "To arrive at the simplest truth requires years of contemplation.",
    "You may think I'm small, but I have a universe inside my mind.",
    "Learn to enjoy every minute of your life. Be happy now. Don't wait for something outside of yourself to make you happy in the future.",
    "The heart that gives, gathers.",
    "Don't learn to do, but learn in doing.",
    "If you chase two rabbits, you catch none.",
    "Every man is guilty of all the good he did not do. ",
    "The strength of a wall is neither greater nor less than the courage of the men who defend it. ",
    "It is easier to fight for one's principles than to live up to them. ",
    "Every failure brings with it the seed of an equivalent success.",
    "Make no small plans for they have no power to stir the soul.",
    "If you want to make God laugh, tell him about your plans. ",]