quotes = [
    "Never whine, never complain, never try to justify yourself.",
    "We must create our own world or we will die from inaction.",
    "By changing nothing, nothing changes.",
    "Take care of your body. It's the only place you have to live.",
    "When obstacles arise, you change your direction to reach your goal; you do not change your decision to get there.",
    "Many of life's failures are people who did not realize how close they were to success when they gave up.",
    "To arrive at the simplest truth requires years of contemplation.",
    "You may think I'm small, but I have a universe inside my mind.",
    "Learn to enjoy every minute of your life. Be happy now. Don't wait for something outside of yourself to make you happy in the future.",
    "The heart that gives, gathers.",
    "Don't learn to do, but learn in doing.",
    "If you chase two rabbits, you catch none.",
    "Every man is guilty of all the good he did not do. ",
    "The strength of a wall is neither greater nor less than the courage of the men who defend it. ",
    "It is easier to fight for one's principles than to live up to them. ",
    "Every failure brings with it the seed of an equivalent success.",
    "Make no small plans for they have no power to stir the soul.",
    "If you want to make God laugh, tell him about your plans. ",]