quotes = [
    "Be where your enemy is not.",
    "Always remember that you are absolutely unique. Just like everyone else. ",
    "It is impossible for a man to learn what he thinks he already knows.",
    "To handle yourself, use your head; to handle others, use your heart.",
    "Love never keeps a man from pursuing his destiny.",
    "When you want something in life, you just gotta reach out and grab it.",
    "If you done it, it ain't bragging.",
    "There is no failure except in no longer trying. There is no defeat except from within, no insurmountable barrier except our own inherent weakness of purpose.",
    "Chase your passion, not your pension. ",
    "It is indeed a radical act of love just to sit down and be quiet for a time by yourself.",
    "As soon as you trust yourself, you will know how to live.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "A wise man will be master of his mind, a fool will be its slave.",
    "Don't let your mind stop you.",
    "Some people want it to happen, some wish it would happen, others make it happen.",
    "Have the courage to follow your heart and intuition. They somehow know what you truly want to become.",
    "Go as far as you can see and you will see further.  ",
    "Nature does not hurry, yet everything is accomplished.",
    "Be content with what you have, rejoice in the way things are. When you realize there is nothing lacking, the whole world belongs to you.",
    "The less you respond to negative people, the more positive your life will become.",
    "The source of a true smile is an awakened mind.",
    "The first step toward getting somewhere is to decide that you are not going to stay where you are.",
    "We must not be afraid of dreaming the seemingly impossible if we want the seemingly impossible to become a reality.",
    "Supreme excellence consists of breaking the enemy's resistance without fighting.",
    "There is nothing quite so tragic as a young cynic.",
    "The way out is in.",
    "The temptation to give up is strongest just before victory.",
    "Everybody by your side ain't on your side.",
    "You don't need a weatherman to know which way the wind blows.",
    "Believe and you're halfway there.",
    "We must learn to live together as brothers or perish together as fools.",
    "A person is only by the thoughts that he chooses.",
    "Peace is letting it be. Letting life flow, letting emotions flow through you.",
    "Don't live the same year 75 times and call it a life.",
    "Lack of emotion causes lack of progress and lack of motivation.",
    "People are doing the best that they can from their own level of consciousness.",
    "Nothing you do is going to matter that much in the long run. Don't take yourself so seriously.",
    "There can be no greater gift than that of giving one's time and energy to help others without expecting anything in return.",
    "To avoid criticism, do nothing, say nothing, and be nothing.",
    "The more knowledge you have, the more you're free to rely on your instincts.",
    "Success is going from failure to failure without losing your enthusiasm",
    "Be a master of change rather than a victim of change.",
    "Don't let what you cannot do interfere with what you can do.",
    "The world is open for play, everything and everybody is mockable in a wonderful way.",
    "The way to change others' minds is with affection, and not anger.",
    "You must live in the present, launch yourself on every wave, find your eternity in each moment. Fools stand on their island of opportunities and look toward another land. There is no other land; there is no other life but this.",
    "It is better to offer no excuse than a bad one. ",
    "The Art of Peace begins with you.",
    "Life is love and love is life.",
    "What you seek is seeking you.",
    "You have power over your mind - not outside events. Realize this, and you will find strength.",
    "Everyone must choose one of two pains: The pain of discipline or the pain of regret.",
    "Many of life's failures are people who did not realize how close they were to success when they gave up.",
    "Victory is always possible for the person who refuses to stop fighting.",
    "Perseverance and spirit have done wonders in all ages. ",
    "Big people don't make people feel small.",
    "Others can stop you temporarily - you are the only one who can do it permanently.",
    "Don't wish it were easier, wish you were better.",
    "We are all here for some special reason.",
    "Either get busy living or get busy dying.",
    "Success is often achieved by those who don't know that failure is inevitable.",
    "When you view failure as feedback, you get more done. When you view failure as a finality, you get nothing done.",
    "The scariest monsters are the ones that lurk within our souls.",
    "It is not the knowing that is difficult, but the doing. ",
    "Be regular and orderly in your life, so that you may be violent and original in your work.",
    "People who avoid failure also avoid success.",
    "There are people who have money and people who are rich.",
    "One's best success comes after their greatest disappointments.",
    "You cannot push anyone up a ladder unless he is willing to climb a little himself.",
    "The day is for honest men, the night for thieves.",
    "Don't be pushed by your problems; be led by your dreams.",
    "Life is ten percent what you experience and ninety percent how you respond to it.",
    "Life is but one dream flowing into another.",
    "None but ourselves can free our minds.",
    "If the happiness and prosperity of other people depend on you, you have nothing to fear anymore.",
    "As a man thinketh in his heart, so shall he be.",
    "Longevity is a fleeting moment that lasts forever.",
    "It is the mark of an educated mind to be able to entertain a thought without accepting it.",
    "When you repeat a mistake, it is not a mistake anymore: it is a decision.",
    "If you want to be successful, you have to jump, there's no way around it.",
    "We will now discuss in a little more detail the Struggle for Existence.",
    "Our anxiety does not empty tomorrow of its sorrows, but only empties today of its strengths.",
    "Education breeds confidence. Confidence breeds hope. Hope breeds peace.",
    "Be happy now, without reason - or you never will be at all.",
    "If it entertains you now but will bore you someday, it's a distraction. Keep looking.",
    "Decide what your truth is. Then live it.",
    "Your gift is something that you can do innately better than anything else.",
    "Absorb what is useful, discard what is useless and add what is specifically your own.  ",
    "Wishing to be friends is quick work, but friendship is a slow ripening fruit.",
    "Whatever you decide to do, make sure it makes you happy.",
    "Be thankful for everything that happens in your life; it's all an experience.",
    "Until you change how you get things done, you'll never know what works best.",
    "It's better to dance than to march through life.",
    "You are what you believe yourself to be.",
    "When you believe in a thing, believe in it all the way, implicitly and unquestionable.",
    "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.",
    "You're only given a little spark of madness. You mustn't lose it.",
    "The strength of a wall is neither greater nor less than the courage of the men who defend it. ",
    "Don't listen to the person who has the answers; listen to the person who has the questions.",
    "Not all those who wander are lost.",
    "Weeds are flowers too, once you get to know them.",
    "We must learn to live together as brothers or perish together as fools.",
    "Great minds are always feared by lesser minds.",
    "If you pick up a starving dog and make him prosperous he will not bite you. This is the principal difference between a dog and man.",
    "Not doing it is certainly the best way to not getting it.  ",
    "A good stance and posture reflect a proper state of mind.",
    "The first rule of business; treat others like they want to treat you.",
    "Fear of death is fear of surrender to Infinity. Learn to surrender, to exist at Infinity while alive, and fear of death dissolves.",
    "Don't settle, and don't struggle.",
    "Others can stop you temporarily - you are the only one who can do it permanently.",
    "Always turn a negative situation into a positive situation.",
    "Be patient and calm; no one can catch fish in anger.",
    "The greater the impact you want to make, the greater your influence needs to be.",
    "Not all those who wander are lost.",
    "Act the way you want to be and soon you'll be the way you act.",
    "The journey, not the destination matters.",
    "He who possesses most must be most afraid of loss.",
    "No man is happy unless he believes he is.",
    "It's better to dance than to march through life.",
    "The more acquaintances you have, the less you know them.",
    "It is better to disappoint people with the truth than to appease them with a lie.",
    "Fools read fast. Geniuses reread.",
    "When at last you are come to the ocean of happiness, do not go back thirsty.",
    "Hope is important because it can make the present moment less difficult to bear. If we believe that tomorrow will be better, we can bear a hardship today.",
    "When something is important enough, you do it even if the odds are not in your favor.",
    "Turn the pain into power.",
    "Cultivate the merry heart, develop the happiness habit, and life will become a continual feast.",
    "It is better to disappoint people with the truth than to appease them with a lie.",
    "Focus on how far you have come in life rather than looking at the accomplishments of others.",
    "Determine never to be idle. No person will have occasion to complain of the want of time who never loses any.",
    "A man sooner or later discovers that he is the master-gardener of his soul, the director of his life.",
    "If you read a lot of books, you're considered well-read. But if you watch a lot of TV, you're not considered well-viewed.",
    "Everyone thinks of changing the world, but no one thinks of changing himself.",
    "There can be no greater gift than that of giving one's time and energy to help others without expecting anything in return.",
    "Don't blame others. it won't make you a better person.",
    "He who possesses most must be most afraid of loss.",
    "It's possible in ways both large or small to make a difference in someone's life.",
    "We are most nearly ourselves when we achieve the seriousness of the child at play.",
    "Maybe you are searching among the branches, for what only appears in the roots.",
    "The salvation of the world lies in the human heart.",
    "Luck is a matter of preparation meeting opportunity.",
    "The future is no more uncertain than the present.",
    "What do we live for, if it is not to make life less difficult for each other?",
    "If you can't, you must. If you must, you can.",
    "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work. ",
    "Yesterday is gone. Tomorrow has not yet come. We have only today.",
    "We are all like the bright moon, we still have our darker side.  ",
    "Superstars think like superstars long before the fans or the press anoint them.",
    "To be totally at leisure for one day is to be immortal for one day. ",
    "Leadership starts at the top.",
    "Circumstances do not make the man, they reveal him.",
    "There is a difference between giving directions and giving direction.",
    "The world only exists in your eyes. You can make it as big or as small as you want.",
    "What the mind can conceive, it can achieve.",
    "Action may not always bring happiness, but there is no happiness without action.",
    "It is best to begin at the beginning.",
    "The purpose of life is to contribute in some way to making things better.",
    "What you seek is seeking you.",
    "If ever you feel like an animal among men, be a lion.",
    "The guest will judge better of a feast than the cook.",
    "Never let your memories be greater than your dreams.",
    "Success is the progressive realization of a worthy goal or ideal.",
    "Those who know, do. Those that understand, teach.",
    "It is those who concentrate on but one thing at a time who advance in this world.",
    "It is not the knowing that is difficult, but the doing. ",
    "Freedom is the only worthy goal in life. It is won by disregarding things that lie beyond our control.",
    "Life's too mysterious to take too serious.",
    "He who leaves the game wins it.",
    "No one returns from a long journey the same person they were before.",
    "The greater the impact you want to make, the greater your influence needs to be.",
    "The only people without problems are those in cemeteries.",
    "Wherever you are is the entry point.",
    "Believe and you're halfway there.",
    "Be thankful for everything that happens in your life; it's all an experience.",
    "The enemy is a very good teacher.",
    "Wit is educated insolence.",
    "Things may come to those who wait, but only the things left by those who hustle.",
    "Heaven is right where you are standing.",
    "Have the fearless attitude of a hero and the loving heart of a child.",
    "Confidence is like a dragon where, for every head cut off, two more heads grow back.",
    "If it entertains you now but will bore you someday, it's a distraction. Keep looking.",
    "Life and the simple beauty of it is too good to pass up.",
    "You cannot always control what goes on outside. But you can always control what goes on inside. ",
    "What's the point in being smart enough to read, if everything you read makes you dumb?",
    "Never give up work. Work gives you meaning and purpose and life is empty without it.",
    "A person without a sense of humor is like a wagon without springs, jolted by every pebble in the road.",
    "If you love life, don't waste time, for time is what life is made up of. ",
    "To live outside the law, you must be honest. ",
    "There is no value in anything until it is finished. ",
    "Argue for your limitations and sure enough, they're yours.",
    "The fear of death is more to be feared, than death itself.",
    "We meet ourselves time and again in a thousand disguises on the path of life.",
    "The fear of death is more to be feared, than death itself.",
    "The soul should always stand ajar, ready to welcome the ecstatic experience.",
    "Not doing it is certainly the best way to not getting it.  ",
    "Failure is acceptable. Not trying is a whole different ball park.",
    "The decisions of our past are the architects of our present.",
    "Remain calm. Be kind.",
    "Everyone has a sense of humor. If you don't laugh at jokes, you probably laugh at opinions.",
    "Never whine, never complain, never try to justify yourself.",
    "We must create our own world or we will die from inaction.",
    "By changing nothing, nothing changes.",
    "Take care of your body. It's the only place you have to live.",
    "When obstacles arise, you change your direction to reach your goal; you do not change your decision to get there.",
    "Many of life's failures are people who did not realize how close they were to success when they gave up.",
    "To arrive at the simplest truth requires years of contemplation.",
    "You may think I'm small, but I have a universe inside my mind.",
    "Learn to enjoy every minute of your life. Be happy now. Don't wait for something outside of yourself to make you happy in the future.",
    "The heart that gives, gathers.",
    "Don't learn to do, but learn in doing.",
    "If you chase two rabbits, you catch none.",
    "Every man is guilty of all the good he did not do. ",
    "The strength of a wall is neither greater nor less than the courage of the men who defend it. ",
    "It is easier to fight for one's principles than to live up to them. ",
    "Every failure brings with it the seed of an equivalent success.",
    "Make no small plans for they have no power to stir the soul.",
    "If you want to make God laugh, tell him about your plans. ",]